export interface Exercise {
  id: string;
  name: string;
  description: string;
  category: 'cognitive' | 'physical';
  duration: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  instructions: string[];
  tips: string[];
  benefits: string[];
  sets?: number;
  reps?: number;
  holdTime?: number;
}

export const exercises: Exercise[] = [
  // Cognitive Exercises
  {
    id: 'start-stop',
    name: 'Start-Stop Technique',
    description: 'Learn to recognize and control your arousal levels by practicing intentional pauses.',
    category: 'cognitive',
    duration: '10-15 mins',
    difficulty: 'beginner',
    instructions: [
      'Begin self-stimulation at a comfortable pace',
      'Focus on your arousal level on a scale of 1-10',
      'When you reach a 7, stop completely',
      'Wait 30 seconds until arousal drops to 4-5',
      'Resume and repeat 3-5 times',
      'Only finish after completing all cycles',
    ],
    tips: [
      'Practice in a relaxed environment',
      'Focus on breathing during pauses',
      'Keep a mental note of what sensations indicate high arousal',
    ],
    benefits: [
      'Builds awareness of arousal levels',
      'Develops ability to control timing',
      'Creates new neural pathways for control',
    ],
    sets: 3,
  },
  {
    id: 'cognitive-reframing',
    name: 'Cognitive Reframing',
    description: 'Transform anxious thoughts about performance into confident, realistic perspectives.',
    category: 'cognitive',
    duration: '5-10 mins',
    difficulty: 'beginner',
    instructions: [
      'Identify a negative thought about performance',
      'Write it down or say it clearly',
      'Challenge the thought: Is it really true?',
      'Create a balanced, realistic alternative',
      'Practice the new thought daily',
    ],
    tips: [
      'Common thoughts to reframe: "I always finish too fast"',
      'Replace with: "I am learning to control my body"',
      'Consistency is key - practice daily',
    ],
    benefits: [
      'Reduces performance anxiety',
      'Builds sexual confidence',
      'Breaks negative thought cycles',
    ],
  },
  {
    id: 'breathing-448',
    name: '4-4-8 Breathing',
    description: 'A powerful breathing technique that activates your parasympathetic nervous system.',
    category: 'cognitive',
    duration: '3-5 mins',
    difficulty: 'beginner',
    instructions: [
      'Sit or lie in a comfortable position',
      'Inhale slowly through your nose for 4 seconds',
      'Hold your breath for 4 seconds',
      'Exhale slowly through your mouth for 8 seconds',
      'Repeat for 5-10 cycles',
    ],
    tips: [
      'Practice this 30 minutes before intimacy',
      'Can be used during sex when feeling close',
      'Focus on the exhale - this is the calming phase',
    ],
    benefits: [
      'Activates relaxation response',
      'Reduces anxiety and tension',
      'Can be used in the moment',
    ],
  },
  {
    id: 'mindfulness',
    name: 'Sensate Focus',
    description: 'A mindfulness practice that helps you stay present during intimate moments.',
    category: 'cognitive',
    duration: '10-15 mins',
    difficulty: 'intermediate',
    instructions: [
      'Find a quiet space and close your eyes',
      'Focus on physical sensations in your body',
      'Notice temperature, pressure, texture',
      'When your mind wanders, gently return focus',
      'Practice being present without judgment',
    ],
    tips: [
      'Start with non-sexual touch awareness',
      'Progress to more intimate awareness over time',
      'The goal is presence, not performance',
    ],
    benefits: [
      'Increases body awareness',
      'Reduces spectatoring during sex',
      'Improves connection with partner',
    ],
  },
  {
    id: 'visualization',
    name: 'Control Visualization',
    description: 'Use mental rehearsal to program your mind for better control.',
    category: 'cognitive',
    duration: '5-10 mins',
    difficulty: 'intermediate',
    instructions: [
      'Close your eyes and relax deeply',
      'Visualize an intimate scenario',
      'See yourself in complete control',
      'Imagine lasting as long as you want',
      'Feel the confidence and satisfaction',
      'Practice this visualization daily',
    ],
    tips: [
      'Make the visualization as vivid as possible',
      'Include emotions: confidence, calm, pleasure',
      'Practice right before sleep for best results',
    ],
    benefits: [
      'Programs subconscious for success',
      'Builds confidence before real situations',
      'Reduces anticipatory anxiety',
    ],
  },
  // Physical Exercises
  {
    id: 'kegel-basic',
    name: 'Basic Kegels',
    description: 'Strengthen your PC muscle - the key muscle for ejaculatory control.',
    category: 'physical',
    duration: '5 mins',
    difficulty: 'beginner',
    instructions: [
      'Locate your PC muscle (stop urination mid-flow)',
      'Contract the muscle and hold for 3 seconds',
      'Release and relax for 3 seconds',
      'Repeat 10-15 times',
      'Do 3 sets with 1 minute rest between',
    ],
    tips: [
      'Don\'t hold your breath',
      'Keep your abs and buttocks relaxed',
      'Quality of contraction matters more than quantity',
    ],
    benefits: [
      'Directly strengthens ejaculation control muscle',
      'Improves erection quality',
      'Results visible in 4-6 weeks',
    ],
    sets: 3,
    reps: 15,
    holdTime: 3,
  },
  {
    id: 'reverse-kegel',
    name: 'Reverse Kegels',
    description: 'Learn to relax your pelvic floor - essential for preventing premature tension.',
    category: 'physical',
    duration: '5 mins',
    difficulty: 'intermediate',
    instructions: [
      'Sit or lie comfortably',
      'Instead of squeezing, push out gently',
      'Imagine you\'re starting to urinate',
      'Hold the relaxed position for 5 seconds',
      'Return to neutral and repeat',
    ],
    tips: [
      'This is the opposite of a kegel',
      'Useful when you feel tension building',
      'Combine with deep breathing',
    ],
    benefits: [
      'Releases pelvic tension',
      'Can delay ejaculation in the moment',
      'Balances kegel training',
    ],
    sets: 3,
    reps: 10,
    holdTime: 5,
  },
  {
    id: 'bridge-hold',
    name: 'Bridge Abduction',
    description: 'Strengthen your core and pelvic region for better overall control.',
    category: 'physical',
    duration: '5 mins',
    difficulty: 'beginner',
    instructions: [
      'Lie on your back, knees bent, feet flat',
      'Lift your hips toward the ceiling',
      'Squeeze your glutes at the top',
      'Hold for 5-10 seconds',
      'Lower slowly and repeat',
    ],
    tips: [
      'Keep your core engaged throughout',
      'Don\'t arch your lower back',
      'Breathe normally while holding',
    ],
    benefits: [
      'Strengthens supporting muscles',
      'Improves pelvic stability',
      'Enhances overall stamina',
    ],
    sets: 3,
    reps: 10,
    holdTime: 10,
  },
  {
    id: 'butterfly-stretch',
    name: 'Lying Butterfly',
    description: 'Release tension in your hip flexors and pelvic region.',
    category: 'physical',
    duration: '3 mins',
    difficulty: 'beginner',
    instructions: [
      'Lie on your back',
      'Bring the soles of your feet together',
      'Let your knees fall open to the sides',
      'Relax your arms by your sides',
      'Hold for 1-2 minutes, breathing deeply',
    ],
    tips: [
      'Use pillows under knees if uncomfortable',
      'Focus on releasing tension with each exhale',
      'Great before sleep',
    ],
    benefits: [
      'Releases hip and groin tension',
      'Improves flexibility',
      'Promotes relaxation',
    ],
    holdTime: 120,
  },
  {
    id: 'pelvic-stretching',
    name: 'Pelvic Floor Stretching',
    description: 'A series of stretches to maintain pelvic flexibility and reduce tension.',
    category: 'physical',
    duration: '5-7 mins',
    difficulty: 'beginner',
    instructions: [
      'Happy Baby: Lie back, grab feet, knees to armpits',
      'Deep Squat: Squat low, hold for 30 seconds',
      'Child\'s Pose: Kneel, sit back, arms forward',
      'Hold each position for 30-60 seconds',
      'Breathe deeply throughout',
    ],
    tips: [
      'Do this routine after sitting for long periods',
      'Never bounce in stretches',
      'Mild discomfort is okay, pain is not',
    ],
    benefits: [
      'Reduces chronic pelvic tension',
      'Improves blood flow to the region',
      'Prevents muscle imbalances',
    ],
  },
  // Additional Cognitive Exercises
  {
    id: 'arousal-scaling',
    name: 'Arousal Scaling',
    description: 'Learn to identify and rate your arousal levels on a 1-10 scale in real-time.',
    category: 'cognitive',
    duration: '5-10 mins',
    difficulty: 'beginner',
    instructions: [
      'Begin self-stimulation slowly',
      'Every 30 seconds, rate your arousal 1-10',
      '1-3: Low arousal, fully in control',
      '4-6: Medium arousal, comfortable',
      '7-8: High arousal, approaching point of no return',
      '9-10: Very high, orgasm imminent',
      'Practice staying in the 5-7 range',
    ],
    tips: [
      'Say the number out loud to build awareness',
      'Notice physical sensations at each level',
      'This skill transfers directly to partner sex',
    ],
    benefits: [
      'Builds precise arousal awareness',
      'Creates early warning system',
      'Foundation for all control techniques',
    ],
  },
  {
    id: 'body-scan',
    name: 'Body Scan Relaxation',
    description: 'Progressive relaxation technique to release tension and reduce performance anxiety.',
    category: 'cognitive',
    duration: '10 mins',
    difficulty: 'beginner',
    instructions: [
      'Lie down in a comfortable position',
      'Close your eyes and take 3 deep breaths',
      'Focus on your feet - notice any tension, then release',
      'Move up to calves, thighs, pelvis',
      'Continue through abdomen, chest, arms',
      'Finish with neck, face, and scalp',
      'Rest in full-body relaxation for 2 minutes',
    ],
    tips: [
      'Practice before sleep for best results',
      'If tension remains, breathe into that area',
      'Use before intimacy to reduce anxiety',
    ],
    benefits: [
      'Releases chronic muscle tension',
      'Reduces performance anxiety',
      'Improves mind-body connection',
    ],
  },
  {
    id: 'edging-practice',
    name: 'Edging Practice',
    description: 'Train your body to approach and retreat from the edge of orgasm repeatedly.',
    category: 'cognitive',
    duration: '15-20 mins',
    difficulty: 'intermediate',
    instructions: [
      'Begin self-stimulation at a comfortable pace',
      'Build arousal to 7-8 on the scale',
      'Stop completely when reaching 8',
      'Wait until arousal drops to 4-5',
      'Resume and repeat 5-10 times',
      'Only finish after completing all cycles',
    ],
    tips: [
      'Use breathing to help reduce arousal during pauses',
      'Track how long you can maintain high arousal',
      'Gradually increase number of edges over weeks',
    ],
    benefits: [
      'Dramatically extends duration',
      'Builds tolerance to high arousal',
      'Creates automatic control responses',
    ],
    sets: 5,
  },
  {
    id: 'squeeze-technique',
    name: 'Squeeze Technique',
    description: 'A physical intervention to reduce arousal when approaching the point of no return.',
    category: 'cognitive',
    duration: '10-15 mins',
    difficulty: 'intermediate',
    instructions: [
      'Build arousal to 7-8 on the scale',
      'When close, squeeze the glans firmly for 10-20 seconds',
      'Apply pressure just below the head',
      'Wait for arousal to drop to 4-5',
      'Resume stimulation and repeat',
      'Practice 3-5 times per session',
    ],
    tips: [
      'Squeeze firmly but not painfully',
      'Can be done by yourself or a partner',
      'Combine with deep breathing for best effect',
    ],
    benefits: [
      'Immediate arousal reduction',
      'Can be used during intercourse',
      'Builds confidence in control ability',
    ],
    sets: 5,
  },
  {
    id: 'distraction-techniques',
    name: 'Distraction Techniques',
    description: 'Mental strategies to reduce arousal peaks during intimate moments.',
    category: 'cognitive',
    duration: '5 mins',
    difficulty: 'beginner',
    instructions: [
      'Learn these techniques to use when arousal spikes:',
      'Mental math: Count backwards from 100 by 7s',
      'Sensory shift: Focus on non-sexual sensations',
      'Breathing focus: Count breaths, extend exhales',
      'Muscle focus: Squeeze and release thigh muscles',
      'Practice each technique during solo sessions',
    ],
    tips: [
      'Have 2-3 techniques ready to use',
      'Don\'t over-distract - stay connected to partner',
      'Use briefly, then return focus to pleasure',
    ],
    benefits: [
      'Provides immediate arousal control',
      'Breaks the arousal spiral',
      'Buys time to regain control',
    ],
  },
  {
    id: 'mindful-masturbation',
    name: 'Mindful Masturbation',
    description: 'Transform solo practice into a training session for better control.',
    category: 'cognitive',
    duration: '15-20 mins',
    difficulty: 'intermediate',
    instructions: [
      'Set aside uninterrupted time',
      'Begin very slowly - focus on every sensation',
      'Vary your touch: pressure, speed, location',
      'Practice staying at medium arousal (5-6)',
      'When arousal rises, slow down or pause',
      'Aim for 15+ minutes before finishing',
    ],
    tips: [
      'No rushing - this is practice, not release',
      'Notice what increases arousal fastest',
      'Build awareness of your personal patterns',
    ],
    benefits: [
      'Builds lasting power',
      'Increases pleasure awareness',
      'Develops automatic control habits',
    ],
  },
  // Additional Physical Exercises
  {
    id: 'advanced-kegels',
    name: 'Advanced Kegels',
    description: 'Intensified PC muscle training with longer holds and more reps.',
    category: 'physical',
    duration: '7 mins',
    difficulty: 'advanced',
    instructions: [
      'Contract your PC muscle as strongly as possible',
      'Hold for 10 seconds at maximum intensity',
      'Release slowly over 5 seconds',
      'Rest for 5 seconds',
      'Repeat 15 times',
      'Do 3 sets with 1 minute rest between',
    ],
    tips: [
      'Only progress here after mastering basic kegels',
      'Quality over quantity - full contraction matters',
      'Stop if you feel fatigue - don\'t overtrain',
    ],
    benefits: [
      'Maximum PC muscle strength',
      'Ability to stop ejaculation mid-orgasm',
      'Enhanced erection quality',
    ],
    sets: 3,
    reps: 15,
    holdTime: 10,
  },
  {
    id: 'quick-flicks',
    name: 'Quick Flicks',
    description: 'Rapid PC contractions to build muscle endurance and quick-response control.',
    category: 'physical',
    duration: '3 mins',
    difficulty: 'intermediate',
    instructions: [
      'Contract your PC muscle quickly',
      'Hold for just 1 second',
      'Release for 1 second',
      'Repeat rapidly 30 times',
      'Rest for 30 seconds',
      'Do 3 sets total',
    ],
    tips: [
      'Focus on speed and rhythm',
      'Breathe normally throughout',
      'Great for building quick-response control',
    ],
    benefits: [
      'Builds muscle endurance',
      'Develops quick contraction ability',
      'Useful for in-the-moment control',
    ],
    sets: 3,
    reps: 30,
    holdTime: 1,
  },
  {
    id: 'hip-flexor-stretch',
    name: 'Hip Flexor Stretch',
    description: 'Release tight hip flexors that contribute to pelvic tension.',
    category: 'physical',
    duration: '4 mins',
    difficulty: 'beginner',
    instructions: [
      'Kneel on your right knee, left foot forward',
      'Keep your back straight, core engaged',
      'Push hips forward gently',
      'Feel the stretch in your right hip front',
      'Hold for 60 seconds',
      'Switch sides and repeat',
    ],
    tips: [
      'Don\'t arch your lower back',
      'Keep the stretch gentle - no bouncing',
      'Breathe deeply into the stretch',
    ],
    benefits: [
      'Releases hip and pelvic tension',
      'Improves sexual positioning comfort',
      'Reduces referred tension to PC muscle',
    ],
    holdTime: 60,
  },
  {
    id: 'deep-squat-hold',
    name: 'Deep Squat Hold',
    description: 'Open your hips and strengthen your pelvic floor in a natural position.',
    category: 'physical',
    duration: '3 mins',
    difficulty: 'beginner',
    instructions: [
      'Stand with feet shoulder-width apart',
      'Squat down as low as comfortable',
      'Keep heels on the ground if possible',
      'Hold your hands together at chest',
      'Keep your back straight',
      'Hold for 30-60 seconds, rest, repeat 3 times',
    ],
    tips: [
      'Use a wall or door frame for balance if needed',
      'It\'s okay if heels come up slightly',
      'Focus on relaxing your pelvic floor in this position',
    ],
    benefits: [
      'Opens hip joints',
      'Strengthens legs and core',
      'Natural pelvic floor stretch',
    ],
    sets: 3,
    holdTime: 45,
  },
  {
    id: 'cat-cow',
    name: 'Cat-Cow Stretch',
    description: 'Mobilize your spine and pelvis while coordinating breath with movement.',
    category: 'physical',
    duration: '3 mins',
    difficulty: 'beginner',
    instructions: [
      'Start on hands and knees',
      'Inhale: Drop belly, lift head and tailbone (Cow)',
      'Exhale: Round spine, tuck chin and tailbone (Cat)',
      'Move slowly with your breath',
      'Repeat 10-15 cycles',
    ],
    tips: [
      'Move smoothly between positions',
      'Feel the movement in your pelvis',
      'Great warm-up before other exercises',
    ],
    benefits: [
      'Mobilizes the spine',
      'Releases pelvic tension',
      'Improves breath-body coordination',
    ],
    reps: 15,
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    description: 'Core stability exercise that strengthens the deep muscles supporting your pelvis.',
    category: 'physical',
    duration: '5 mins',
    difficulty: 'intermediate',
    instructions: [
      'Lie on your back, arms pointed to ceiling',
      'Lift legs to 90 degrees at hips and knees',
      'Press lower back firmly into the floor',
      'Slowly extend right arm back and left leg forward',
      'Return to start, switch sides',
      'Do 10 reps per side, 3 sets',
    ],
    tips: [
      'Keep lower back pressed down throughout',
      'Move slowly and controlled',
      'Breathe out as you extend',
    ],
    benefits: [
      'Strengthens deep core muscles',
      'Improves pelvic stability',
      'Better control during sex positions',
    ],
    sets: 3,
    reps: 10,
  },
  {
    id: 'glute-bridges',
    name: 'Glute Bridges',
    description: 'Strengthen glutes and improve hip thrust power and endurance.',
    category: 'physical',
    duration: '5 mins',
    difficulty: 'beginner',
    instructions: [
      'Lie on back, knees bent, feet flat on floor',
      'Squeeze glutes and lift hips toward ceiling',
      'Hold at the top for 2 seconds',
      'Lower slowly back down',
      'Repeat 15 times, do 3 sets',
    ],
    tips: [
      'Drive through your heels',
      'Squeeze glutes hard at the top',
      'Don\'t hyperextend your lower back',
    ],
    benefits: [
      'Stronger glutes for better stamina',
      'Improved hip thrust endurance',
      'Better pelvic control',
    ],
    sets: 3,
    reps: 15,
    holdTime: 2,
  },
  {
    id: 'plank-hold',
    name: 'Plank Hold',
    description: 'Build core endurance that translates to better stamina and control.',
    category: 'physical',
    duration: '3 mins',
    difficulty: 'intermediate',
    instructions: [
      'Start in a push-up position',
      'Lower to forearms, elbows under shoulders',
      'Keep body in a straight line',
      'Engage core and glutes',
      'Hold for 30-60 seconds',
      'Rest and repeat 3 times',
    ],
    tips: [
      'Don\'t let hips sag or pike up',
      'Breathe steadily throughout',
      'Start with shorter holds and build up',
    ],
    benefits: [
      'Builds core endurance',
      'Improves body control',
      'Increases stamina for sex positions',
    ],
    sets: 3,
    holdTime: 45,
  },
];

export const getExerciseById = (id: string): Exercise | undefined => {
  return exercises.find(e => e.id === id);
};

export const getExercisesByCategory = (category: 'cognitive' | 'physical'): Exercise[] => {
  return exercises.filter(e => e.category === category);
};
